# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               我的学习笔记-winderay
tagline:             'A Jekyll theme'
description:         '基于Github pages搭建的个人博客站点，用于记学习和记录个人博客搭建方法及相关知识。'
url:                 http://winderay.github.io/winderay
baseurl:             /winderay
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             1.0.0
